### ISSUE TITLE
关于btc SigVins()函数报错的疑问

### ISSUE THREAD

**Issue by arvin-lau** [moremorefun/go-dc-wallet#26]
该函数内部调用了txSigHash := txscript.NewTxSigHashes(tx, nil) ,看报错信息是由于第二个参数为nil导致的,这个问题困扰了我快两天了,望作者解惑

报错信息如下:

`/usr/local/go1.18.10/go/bin/go tool test2json -t /private/var/folders/r8/mmzcbhd53652kh1k6gdlz1_80000gn/T/GoLand/___TestTransferBtc_in_go_dc_wallet_hbtc.test -test.v -test.paniconexit0 -test.run ^\QTestTransferBtc\E$
=== RUN   TestTransferBtc
--- FAIL: TestTransferBtc (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1003e5c4b]

goroutine 22 [running]:
testing.tRunner.func1.2({0x100476180, 0x10093ebd0})
	/usr/local/go1.18.10/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go1.18.10/go/src/testing/testing.go:1392 +0x39f
panic({0x100476180, 0x10093ebd0})
	/usr/local/go1.18.10/go/src/runtime/panic.go:838 +0x207
github.com/btcsuite/btcd/txscript.NewTxSigHashes(0xc000445000, {0x0, 0x0})
	/Users/xiaodong/go/pkg/mod/github.com/btcsuite/btcd@v0.23.1/txscript/hashcache.go:239 +0x16b
go-dc-wallet/hbtc.SigVins(0x100948780, 0xc000445000, {0xc00012af18, 0x1, 0x100f50bd8?})
	/Users/xiaodong/go/src/go-dc-wallet/hbtc/help.go:515 +0x55
go-dc-wallet/hbtc.BtcMakeTx(0x10006c7b6?, {0xc00012af18, 0x1, 0x1}, {0xc00012af20, 0x1, 0xc000063720?}, 0x2710, {0x100510b87, 0x22})
	/Users/xiaodong/go/src/go-dc-wallet/hbtc/help.go:157 +0x3fb
go-dc-wallet/hbtc.TestTransferBtc(0x11?)
	/Users/xiaodong/go/src/go-dc-wallet/hbtc/btcMakeTx_test.go:23 +0x194
testing.tRunner(0xc00045e4e0, 0x100600db8)
	/usr/local/go1.18.10/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go1.18.10/go/src/testing/testing.go:1486 +0x35f

Process finished with the exit code 1
`

**Comment by moremorefun** [comment]
请参考如下例子修改，库的版本更新了，参数有变化
https://pkg.go.dev/github.com/btcsuite/btcd/txscript#example-SignTxOutput
